### ISSUE TITLE
invert a binary tree

### ISSUE THREAD

**Issue by prakashn27** [AlgorithmCrackers/Interview-Questions#10]
Possible solution of max Howel interview question? have to test it before integrating it. 
http://www.quora.com/What-is-the-algorithmic-approach-to-invert-a-given-binary-tree

**Comment by santhoshvai** [comment]
that solution is not too good, the one below must work. Basic recursion qn in my opinion.
```
void reverse(Node root) {
    if (root == null) { return }; 
   reverse(root.Left);
   reverse(root.Right);
}
```

**Comment by prakashn27** [comment]
where do we set the left and right tree after inversing??

**Comment by santhoshvai** [comment]
Lol.. i forgot to add that.. I have edited it now..

**Comment by prakashn27** [comment]
Yep. awesome dude. U r now selected in gogle :)

**Comment by prakashn27** [comment]
we will close the issue when we implement the structure and add this code into it.

**Comment by santhoshvai** [comment]
See https://github.com/AlgorithmCrackers/Interview-Questions/tree/master/04_Trees_and_Graphs/invert-binary-tree
