### ISSUE TITLE
can you add more comments to the individual functions, I dont understand what is happening

### ISSUE THREAD

**Issue by santhoshvai** [AlgorithmCrackers/Interview-Questions#12]
Regarding c95b578b8e3f6acacbe0397ea135e917d4c3180e

**Comment by prakashn27** [comment]
added the comments. See and let me know.

**Comment by santhoshvai** [comment]
Can understand now! Thanks!

**Comment by prakashn27** [comment]
We will close this issue once we add the sqlite part. in python code. Take a look at it if u have time.

**Comment by santhoshvai** [comment]
URL shortner has become a popular system design question now, we should do something else in the future, closing this issue as it is stale
