### ISSUE TITLE
Place questions in seperate folder named Questions

### ISSUE THREAD

**Issue by prakashn27** [AlgorithmCrackers/Interview-Questions#14]
I have overwritten ur questions folder. Please redo it . @santhoshvai

**Comment by santhoshvai** [comment]
Where are the files? I dont have a local copy. Please revert the commit and just move the questions. I cannot do this.

You have moved the java questions but not the others. I dont understand why you cant move 2 more files like that.

**Comment by prakashn27** [comment]
dai i already have a folder named misc. It did not merge it got replaced when i did it.

**Comment by prakashn27** [comment]
@santhoshvai : ur top coder repo has to be updated and wiki is to be written.
