### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by santhoshvai** [AlgorithmCrackers/Interview-Questions#16]
In 44ded4ca95babf931e8addedab9b387150a9a9c6, minor typo for permutation. 

P.S: Also, do document the code well. Your recent commits have been very good but they lack in documentation. When someone else to looks at your code, it takes a while to understand.

**Comment by prakashn27** [comment]
okay dude. Can you specify the typo line number. I am still not able to find it. @santhoshvai

**Comment by santhoshvai** [comment]
@prakashn27 the folder name

**Comment by prakashn27** [comment]
@santhoshvai  8ebd0af41a7bfd3004eb6255157173122a4541b0 check this one. Let me know if it is still unclear
PS added a new method

**Comment by santhoshvai** [comment]
Clear now :) 

Bug is still there. String/**Permutaion**/Solution.py

**Comment by santhoshvai** [comment]
Also something is wrong with `Interview-Questions/Trees/ConnectedComponants/ `, I think you have pushed a incomplete answer

**Comment by prakashn27** [comment]
deleted the folder will add correct code before pushing
