### ISSUE TITLE
Url shortener doesnt have any OO design. It just seems like a problem being solved. 

### ISSUE THREAD

**Issue by santhoshvai** [AlgorithmCrackers/Interview-Questions#17]
https://github.com/AlgorithmCrackers/Interview-Questions/tree/master/07_Object-Oriented_Design/Url_shortner

Fits in someother category?

**Comment by prakashn27** [comment]
@santhoshvai  I would suggest to adding it in system_design questions. This is one way of designing URL shortner right?

**Comment by santhoshvai** [comment]
yes this a good url shortener. But of course it doesnt fit system design. We are not designing a whole software system at all. We are only handling the shortening. System design is where you habdle network requests, database etc. The whole thing.

**Comment by prakashn27** [comment]
we need to implement database in this model. i saw this question in design rounds of interviews. That is why i tried to do this question.
