### ISSUE TITLE
add to readme

### ISSUE THREAD

**Issue by santhoshvai** [AlgorithmCrackers/Interview-Questions#25]
for 6610190f601c0dec148fcf82f541077875e3a2ae update the questions to readme as well.

**Comment by prakashn27** [comment]
added

**Comment by santhoshvai** [comment]
@prakashn27  where?  i dont see it in https://github.com/AlgorithmCrackers/Interview-Questions/blob/master/00_Arrays/README.md

**Comment by prakashn27** [comment]
@santhoshvai I have updated in the wiki man. When did you change the model. I thgt we are always updating the wiki. ?? https://github.com/AlgorithmCrackers/Interview-Questions/wiki/Questions_list

**Comment by santhoshvai** [comment]
I have already informed this to you. The problem comes from finding which answer is the one for that corresponding question.  The ideal way is to add question in **BOTH readme and wiki**. 

See https://github.com/AlgorithmCrackers/Interview-Questions/tree/master/04_Trees_and_Graphs/src

In readme if we use the format " full question - questionCode " - then its easy to find the answer.

**Comment by santhoshvai** [comment]
README.md is more direct.. answers can be directly linked.. from them

**Comment by prakashn27** [comment]
Added.
