### ISSUE TITLE
Trees and graphs has as extra src folder. 

### ISSUE THREAD

**Issue by prakashn27** [AlgorithmCrackers/Interview-Questions#26]
@santhoshvai

**Comment by santhoshvai** [comment]
That is okay.. can be easily imported to eclipse

**Comment by prakashn27** [comment]
if someone wants to add to tree folder they may get into problem that is why asking you to change the structure.

**Comment by santhoshvai** [comment]
What is the problem? Just add to the sub-folder. People who add here are software developers, they know to add to sub folder rather than the root.
