### ISSUE TITLE
What do you think is the run time of this function?

### ISSUE THREAD

**Issue by prakashn27** [AlgorithmCrackers/Interview-Questions#4]
[subsets.java](https://github.com/AlgorithmCrackers/Interview-Questions/blob/master/Bit-Hacks/Subsets/Subsets.java)
i think it is O(2^length * length)
what do u think?

**Comment by santhoshvai** [comment]
I dont understand how the program works at all, A facetime explanation is needed :(

**Comment by prakashn27** [comment]
http://ideone.com/fvSQC3
for ref.

**Comment by prakashn27** [comment]
updated the comments. let me know if u still have doubt.
