### ISSUE TITLE
Time complexity

### ISSUE THREAD

**Issue by prakashn27** [AlgorithmCrackers/Interview-Questions#5]
http://www.programcreek.com/2013/02/leetcode-longest-substring-without-repeating-characters-java/

see java solution 2

why is the time complexity O(n^3)?

**Comment by prakashn27** [comment]
it is O(n^3 ). 
source from reditters
http://www.reddit.com/r/learnprogramming/comments/2s4rdq/complexity_doubt/

**Comment by santhoshvai** [comment]
Seems like posting in reddit gets good answers and increases our knowledge
