### ISSUE TITLE
JAVA: define and add annotations

### ISSUE THREAD

**Issue by prakashn27** [AlgorithmCrackers/Interview-Questions#8]
lets add annotations for author name, date defined, details

https://docs.oracle.com/javase/tutorial/java/annotations/declaring.html

This can be a best practice for java programs.

**Comment by santhoshvai** [comment]
This looks like a overkill for me. I dont remember seeing this even in google java code, where many best practices are mandatory. I may be wrong.; Show me an example code in github from the top tier employees if I am indeed wrong.

**Comment by prakashn27** [comment]
I am using annotations in my experience. So thought this would be a good way. Anyway we can stick with the format which is good for all the languages.
